[[redirects]]
    from = "/*"
    to = "404.html"
    status = 404

# External redirects
[[redirects]]
    from = "/gh"
    to = "https://github.com/ohman-emil"
    status = 301

[[redirects]]
    from = "/ga"
    to = "https://github.com/ohman-emil/GA"
    status = 301%